Submit should be inside <form>
ChangoMan/gatsby-starter-strata pull request #5
Opened 2020-02-23 19:16 UTC by mattcanty

Might need some tweaking visually. I will update proposal if I sort it myself.

2020-03-28 15:41 UTC, GhassenRjab requested changes

2020-03-28 15:41 UTC, GhassenRjab commented on src/pages/index.js
> +                                  <ul className="actions">
The code is not well indented here.
This `ul` is a sibling to the previous `div`.

2020-04-03 18:08 UTC, GhassenRjab approved these changes

2020-04-04 15:16 UTC, merged

2020-04-04 15:16 UTC, ChangoMan commented
Thanks!